# basic options
title: Martyna Lukaszewicz
author: Martyna Lukaszewicz
email: martyna[at]uidaho[dot]edu
description: Bioinformatics and Computational Biology
github_username:  martynalukaszewicz

# Build settings
markdown: kramdown
theme: minima
