# basic options
title: Martyna Lukaszewicz
email: martyna[at]uidaho[dot]edu
description: Bioinformatics and Computational Biology
github_username: martynalukaszewicz
linkedin_username: martyna-lukaszewicz-95938b80  

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default
      

# Build settings
markdown: kramdown
theme: minima
