# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
# basic options
title: Martyna Lukaszewicz
first_name: Martyna
last_name: Lukaszewicz
email: martyna.lukaszewicz[at]gmail[dot]com
#author: Jekyll
description: 



# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 
#google-scholar:
scholar_userid: ATN-Q6kAAAAJ
orcid_id: 0000-0002-0539-0883



# Build settings
markdown: kramdown
theme: minima

plugins: 
  - jekyll-sitemap
  - jekyll/scholar
