# basic options
title: Martyna Lukaszewicz
email: martyna[at]uidaho[dot]edu
description: Bioinformatics and Computational Biology
github_username: martynalukaszewicz {:target="_blank"}
linkedin_username: martyna-lukaszewicz {:target="_blank"}

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default
      

# Build settings
markdown: kramdown
theme: minima
