# basic options
title: Martyna Lukaszewicz
email: lukas.mrty[at]gmail[dot]com
author: Jekyll
description: 
github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 


# Build settings
markdown: kramdown
theme: minima

plugins: 
  - jekyll-sitemap
