# basic options
title: Martyna Lukaszewicz
#email: martyna.lukaszewicz[at]gmail[dot]com
author: Jekyll
description: 
github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 
#google-scholar:
scholar_userid: ATN-Q6kAAAAJ
#email: martyna.lukaszewicz[at]gmail[dot]com



# Build settings
markdown: kramdown
theme: minima

plugins: 
  - jekyll-sitemap
  #- jekyll/scholar
