# basic options
title: Martyna Lukaszewicz
author: Jekyll
email: martyna[at]uidaho[dot]edu
description: Bioinformatics and Computational Biology 
github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 


# Build settings
markdown: kramdown
theme: minima
