# basic options
title: Martyna Lukaszewicz
author: Bioinformatics and Computational Biology
email: martyna[at]uidaho[dot]edu
description: [Jekyll](https://jekyllrb.com/)  
github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 


# Build settings
markdown: kramdown
theme: minima
