# basic options
title: Martyna Lukaszewicz
#email: martyna[at]uidaho[dot]edu
#email: lukas.mrty[at]gmail[dot]com
author: Jekyll
description: 
github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 
email: "martyna.lukaszewicz@gmail.com"
#martyna.lukaszewicz[at]gmail[dot]com
# Build settings
markdown: kramdown
theme: minima
plugins: 
  - jekyll-sitemap


