# basic options
title: Martyna Lukaszewicz
author: Jekyll
description: >
martyna.lukaszewicz[at]gmail[dot]com



github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 




# Build settings
markdown: kramdown
theme: minima
plugins: 
  - jekyll-sitemap
