plugins:
  - jekyll-seo-tag
  
# basic options
title: Martyna Lukaszewicz
email: martyna[at]uidaho[dot]edu
author: Jekyll
description: Biostatistician learning that data science. 
github_username: martynalukaszewicz 
linkedin_username: martyna-lukaszewicz 


# Build settings
markdown: kramdown
theme: minima
